version: '2'

services:
  web:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db